name: Publish Podspec

on:
  push:
    tags:
      - '*'

jobs:
  publish:
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v2

      - name: Publish podspec
        run: |
          set -o pipefail
          git config --global user.name "github-actions[bot]"
          git config --global user.email "github-actions[bot]@users.noreply.github.com"
          pod repo add podrepo https://${PODREPO_GITHUB_API_TOKEN}@github.com/${PODREPO_GITHUB_REPOSITORY}.git
          pod lib lint --quick
          pod repo push podrepo --use-json
        env:
          PODREPO_GITHUB_API_TOKEN: ${{ secrets.PODREPO_GITHUB_API_TOKEN }}
          PODREPO_GITHUB_REPOSITORY: ElfSundae/CocoaPods-Specs
