name: Publish Podspec

on:
  push:
    tags:
      - '*'

jobs:
  publish:
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v2

      - name: Publish Podspec
        run: |
          set -o pipefail
          git config --global user.name "github-actions[bot]"
          git config --global user.email "github-actions[bot]@users.noreply.github.com"
          pod repo add podspecs https://${PODREPO_GITHUB_API_TOKEN}@github.com/${GITHUB_REPOSITORY}.git
          pod repo push podspecs --use-json
        env:
          PODREPO_GITHUB_API_TOKEN: ${{ secrets.PODREPO_GITHUB_API_TOKEN }}
          GITHUB_REPOSITORY: ElfSundae/CocoaPods-Specs
