name: Test

on: push

jobs:
  test:
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v2

      - name: Test
        run: |
          pod --version
          pod repo list
          pod repo add podspecs https://github.com/ElfSundae/CocoaPods-Specs.git
          pod lib lint --verbose || true
          pod repo list
